### ISSUE TITLE
Missing "xmlns" attribute of the "svg" element

### ISSUE THREAD

**Issue by dessita** [jgarber623/svgeez#24]
Can't link use the generated file as  external to allow caching, because of  this.

**Comment by jgarber623** [comment]
@dessita Thanks for filing this issue. Can you provide a little more detail regarding the problem you're having (e.g. a code example demonstrating the issue)?

**Comment by dhovart** [comment]
I just tried svgeez and had the same issue - noticed my icons wouldn't appear in chrome nor firefox unless I added manually the xmlns attribute back.

Chrome version: 54.0.2840.71
Firefox version: 49.0.2

**Comment by jgarber623** [comment]
@dhovart Can you provide a link to a code sample demonstrating this issue? Unfortunately, I'm not able to replicate it [on my own site](https://sixtwothree.org).

Thanks!

**Comment by dhovart** [comment]
> Can you provide a link to a code sample demonstrating this issue?

Unfortunately not, it's a rails app with closed source currently in development.

I think that the initial issue doesn’t state clearly enough that in our case, the <code>xlink:href</code> attribute doesn't consist of a fragment identifier only but of a _full IRI_ to an external svg. This enables caching the svg file by the browser instead of having the svg definitions embedded on every html page.

It doesn't work without if the namespace is not specified in the external svg being linked.
I'll try to create a small proof of concept later today so that it's clearer for everybody.

**Comment by dhovart** [comment]
If you wish I can update the README to add a section on working with svg sprites using an external source.
Browser support is not excellent but there are some [pretty good polyfills](https://github.com/jonathantneal/svg4everybody) around.

**Comment by dhovart** [comment]
Small proof of concept here:  http://www.denishovart.com/demo/
The second icon is not showing because the svg is missing the xmlns attribute.

**Comment by jgarber623** [comment]
Resolved by @dhovart's PR #25.

Thanks for the feedback and bug report, @dessita!
